version: '3.6'

services:
  smarthome-controlapi:
    container_name: smarthome-controlapi
    image: youruser/smarthome-controlapi:1.0.1
    build:
      context: .
      dockerfile: SmartHome.ControlApi/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
     - "8080:8080"   
  consul-discovery:
    container_name: consul-discovery
    image: consul
    ports:
      - "8500:8500"