version: '3.6'

services:
  smarthome-controlapi:
    container_name: smarthome-controlapi
    image: youruser/smarthome-controlapi:1.0.1
    build:
      context: .
      dockerfile: SmartHome.ControlApi/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
     - "8080:8080"   

  smarthome-eventlogapi:
    container_name: smarthome-eventlogapi
    image: youruser/smarthome-eventlogapi:1.0.1
    build:
      context: .
      dockerfile: SmartHome.EventlogApi/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8090
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
     - "8090:8090"   

  smarthome-authapi:
    container_name: smarthome-authapi
    image: youruser/smarthome-authapi:1.0.1
    build:
      context: .
      dockerfile: SmartHome.AuthApi/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8088
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
     - "8088:8088"   

  smarthome-identity:
    container_name: smarthome-identity
    image: youruser/smarthome-identity:1.0.1
    build:
      context: .
      dockerfile: SmartHome.IdentityServer/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8095
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
     - "8095:8095" 

  consul-discovery:
    container_name: consul-discovery
    image: consul
    ports:
      - "8500:8500"